# Generated by Django 5.2.4 on 2025-07-22 14:11

import admin_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0002_productimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images', validators=[admin_backend.models.validate_image_extension]),
        ),
    ]
