# Generated by Django 5.2.4 on 2025-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
